drop table if exists order_line CASCADE;
drop table if exists orders CASCADE;
drop table if exists goods CASCADE;
drop sequence if exists my_sequence;

create table goods
(
    id    bigint generated by default as identity,
    name  varchar(255) not null,
    price double       not null,
    primary key (id)
);
create table orders
(
    id      bigint generated by default as identity,
    address varchar(255) not null,
    client  varchar(255) not null,
    date    date         not null,
    primary key (id)
);
create table order_line
(
    id       bigint generated by default as identity,
    count    integer not null,
    goods_id bigint  not null,
    order_id bigint  not null,
    primary key (id),
    foreign key (goods_id) references goods (id),
    foreign key (order_id) references orders (id),
    unique (order_id, goods_id)
);
create sequence my_sequence start with 100 increment by 1;